import { PlaceSeed } from "@tteum/contracts";

export const PLACE_SEEDS: PlaceSeed[] = [
  {
    id: "deoksugung-stonewall",
    name: "덕수궁 돌담길",
    areaName: "시청·서소문",
    latitude: 37.5658,
    longitude: 126.9752,
    type: "walk",
    moods: ["empty", "walk"],
    indoor: false,
    minStayMinutes: 15,
    idealStayMinutes: 25,
    maxStayMinutes: 45,
    estimatedCostWon: 0,
    openTime: "00:00",
    closeTime: "24:00",
    verifiedAt: "2026-09-12",
    accessibility: { wheelchair: true, seating: true },
  },
  {
    id: "jeongdong-observatory",
    name: "정동전망대 (서소문청사 13층)",
    areaName: "시청·서소문",
    latitude: 37.5645,
    longitude: 126.9749,
    type: "view",
    moods: ["empty", "stay"],
    indoor: true,
    minStayMinutes: 15,
    idealStayMinutes: 30,
    maxStayMinutes: 50,
    estimatedCostWon: 3500, // 카페 음료 기준
    openTime: "09:00",
    closeTime: "21:00",
    verifiedAt: "2026-09-12",
    accessibility: { wheelchair: true, toilet: true, seating: true },
  },
  {
    id: "seoul-library-rooftop",
    name: "서울도서관 옥상 하늘뜰",
    areaName: "서울광장·시청",
    latitude: 37.5663,
    longitude: 126.9779,
    type: "view",
    moods: ["empty", "stay"],
    indoor: false,
    minStayMinutes: 10,
    idealStayMinutes: 20,
    maxStayMinutes: 35,
    estimatedCostWon: 0,
    openTime: "09:00",
    closeTime: "19:00",
    closedDays: ["월요일"],
    verifiedAt: "2026-09-12",
    accessibility: { wheelchair: true, toilet: true, seating: true },
  },
  {
    id: "seoul-city-hall-green-wall",
    name: "서울시청 수직정원 로비",
    areaName: "서울광장·시청",
    latitude: 37.5663,
    longitude: 126.9779,
    type: "indoor-walk" as any,
    moods: ["empty", "stay"],
    indoor: true,
    minStayMinutes: 10,
    idealStayMinutes: 20,
    maxStayMinutes: 30,
    estimatedCostWon: 0,
    openTime: "08:30",
    closeTime: "20:00",
    verifiedAt: "2026-09-12",
    accessibility: { wheelchair: true, toilet: true, seating: true },
  },
  {
    id: "hwangudan-sacred-site",
    name: "환구단과 석고",
    areaName: "소공동·시청",
    latitude: 37.5650,
    longitude: 126.9798,
    type: "walk",
    moods: ["empty", "walk"],
    indoor: false,
    minStayMinutes: 10,
    idealStayMinutes: 20,
    maxStayMinutes: 35,
    estimatedCostWon: 0,
    openTime: "00:00",
    closeTime: "24:00",
    verifiedAt: "2026-09-12",
    accessibility: { seating: true },
  },
  {
    id: "cheonggye-plaza-spring",
    name: "청계광장과 스프링 분수대",
    areaName: "광화문·청계천",
    latitude: 37.5691,
    longitude: 126.9778,
    type: "walk",
    moods: ["walk", "discover"],
    indoor: false,
    minStayMinutes: 15,
    idealStayMinutes: 25,
    maxStayMinutes: 40,
    estimatedCostWon: 0,
    openTime: "00:00",
    closeTime: "24:00",
    verifiedAt: "2026-09-12",
    accessibility: { wheelchair: true, seating: true },
  },
  {
    id: "cheonggye-samilgyo-under",
    name: "청계천 삼일교 베를린광장 산책로",
    areaName: "을지로·종로",
    latitude: 37.5684,
    longitude: 126.9877,
    type: "walk",
    moods: ["walk", "empty"],
    indoor: false,
    minStayMinutes: 20,
    idealStayMinutes: 30,
    maxStayMinutes: 60,
    estimatedCostWon: 0,
    openTime: "00:00",
    closeTime: "24:00",
    verifiedAt: "2026-09-12",
    accessibility: { seating: true },
  },
  {
    id: "gwanghwamun-square-booklounge",
    name: "광화문광장 야외 책마당",
    areaName: "광화문",
    latitude: 37.5714,
    longitude: 126.9768,
    type: "park",
    moods: ["stay", "discover"],
    indoor: false,
    minStayMinutes: 15,
    idealStayMinutes: 35,
    maxStayMinutes: 60,
    estimatedCostWon: 0,
    openTime: "10:00",
    closeTime: "21:00",
    verifiedAt: "2026-09-12",
    accessibility: { wheelchair: true, seating: true },
  },
  {
    id: "sejong-lounge-art",
    name: "세종문화회관 세종라운지",
    areaName: "광화문",
    latitude: 37.5723,
    longitude: 126.9756,
    type: "library",
    moods: ["stay", "empty"],
    indoor: true,
    minStayMinutes: 15,
    idealStayMinutes: 30,
    maxStayMinutes: 50,
    estimatedCostWon: 0,
    openTime: "10:00",
    closeTime: "21:30",
    verifiedAt: "2026-09-12",
    accessibility: { wheelchair: true, toilet: true, seating: true },
  },
  {
    id: "seoul-historical-museum-garden",
    name: "서울역사박물관 야외 후원",
    areaName: "신문로·광화문",
    latitude: 37.5704,
    longitude: 126.9706,
    type: "park",
    moods: ["empty", "walk"],
    indoor: false,
    minStayMinutes: 20,
    idealStayMinutes: 35,
    maxStayMinutes: 60,
    estimatedCostWon: 0,
    openTime: "09:00",
    closeTime: "19:00",
    closedDays: ["월요일"],
    verifiedAt: "2026-09-12",
    accessibility: { wheelchair: true, seating: true },
  },
  {
    id: "gyeonghuigung-tranquil",
    name: "경희궁 숭정전 뒤뜰 언덕",
    areaName: "신문로·광화문",
    latitude: 37.5712,
    longitude: 126.9682,
    type: "park",
    moods: ["empty", "walk"],
    indoor: false,
    minStayMinutes: 20,
    idealStayMinutes: 35,
    maxStayMinutes: 55,
    estimatedCostWon: 0,
    openTime: "09:00",
    closeTime: "18:00",
    closedDays: ["월요일"],
    verifiedAt: "2026-09-12",
    accessibility: { seating: true },
  },
  {
    id: "ilmin-museum-pillar-bookstore",
    name: "일민미술관 기둥서점",
    areaName: "광화문·세종대로",
    latitude: 37.5698,
    longitude: 126.9777,
    type: "library",
    moods: ["discover", "stay"],
    indoor: true,
    minStayMinutes: 15,
    idealStayMinutes: 30,
    maxStayMinutes: 45,
    estimatedCostWon: 0,
    openTime: "11:00",
    closeTime: "19:00",
    closedDays: ["월요일"],
    verifiedAt: "2026-09-12",
    accessibility: { wheelchair: true, seating: true },
  },
  {
    id: "national-museum-korean-contemporary-rooftop",
    name: "대한민국역사박물관 8층 옥상정원",
    areaName: "광화문",
    latitude: 37.5738,
    longitude: 126.9780,
    type: "view",
    moods: ["discover", "empty"],
    indoor: false,
    minStayMinutes: 15,
    idealStayMinutes: 25,
    maxStayMinutes: 40,
    estimatedCostWon: 0,
    openTime: "10:00",
    closeTime: "21:00",
    verifiedAt: "2026-09-12",
    accessibility: { wheelchair: true, toilet: true, seating: true },
  },
  {
    id: "mmca-seoul-courtyard",
    name: "국립현대미술관 서울 야외마당",
    areaName: "소격동·삼청",
    latitude: 37.5794,
    longitude: 126.9800,
    type: "park",
    moods: ["empty", "walk", "stay"],
    indoor: false,
    minStayMinutes: 20,
    idealStayMinutes: 40,
    maxStayMinutes: 70,
    estimatedCostWon: 0,
    openTime: "10:00",
    closeTime: "21:00",
    verifiedAt: "2026-09-12",
    accessibility: { wheelchair: true, seating: true, toilet: true },
  },
  {
    id: "seoul-craft-museum-garden",
    name: "서울공예박물관 야외 잔디마당과 은행나무",
    areaName: "안국·인사동",
    latitude: 37.5765,
    longitude: 126.9847,
    type: "park",
    moods: ["walk", "stay", "empty"],
    indoor: false,
    minStayMinutes: 15,
    idealStayMinutes: 30,
    maxStayMinutes: 50,
    estimatedCostWon: 0,
    openTime: "10:00",
    closeTime: "20:00",
    closedDays: ["월요일"],
    verifiedAt: "2026-09-12",
    accessibility: { wheelchair: true, seating: true },
  },
  {
    id: "ujungchongguk-quiet-garden",
    name: "우정총국 도심 속 작은 쉼터",
    areaName: "조계사·인사동",
    latitude: 37.5739,
    longitude: 126.9829,
    type: "park",
    moods: ["empty", "stay"],
    indoor: false,
    minStayMinutes: 10,
    idealStayMinutes: 20,
    maxStayMinutes: 35,
    estimatedCostWon: 0,
    openTime: "00:00",
    closeTime: "24:00",
    verifiedAt: "2026-09-12",
    accessibility: { seating: true },
  },
  {
    id: "jogyesa-lotus-courtyard",
    name: "조계사 연꽃마당과 백송",
    areaName: "조계사·인사동",
    latitude: 37.5742,
    longitude: 126.9821,
    type: "walk",
    moods: ["empty", "stay"],
    indoor: false,
    minStayMinutes: 15,
    idealStayMinutes: 25,
    maxStayMinutes: 45,
    estimatedCostWon: 0,
    openTime: "04:00",
    closeTime: "22:00",
    verifiedAt: "2026-09-12",
    accessibility: { wheelchair: true, seating: true },
  },
  {
    id: "bosingak-belfry-square",
    name: "보신각 뒤편 쌈지마당",
    areaName: "종각·종로",
    latitude: 37.5698,
    longitude: 126.9835,
    type: "walk",
    moods: ["empty", "walk"],
    indoor: false,
    minStayMinutes: 10,
    idealStayMinutes: 20,
    maxStayMinutes: 30,
    estimatedCostWon: 0,
    openTime: "00:00",
    closeTime: "24:00",
    verifiedAt: "2026-09-12",
    accessibility: { seating: true },
  },
  {
    id: "anguk-yunboseon-gil",
    name: "안국동 윤보선길 골목 산책",
    areaName: "북촌·안국",
    latitude: 37.5786,
    longitude: 126.9834,
    type: "walk",
    moods: ["walk", "discover"],
    indoor: false,
    minStayMinutes: 20,
    idealStayMinutes: 35,
    maxStayMinutes: 60,
    estimatedCostWon: 0,
    openTime: "00:00",
    closeTime: "24:00",
    verifiedAt: "2026-09-12",
    accessibility: { seating: false },
  },
  {
    id: "euljiro-lighting-street-alley",
    name: "을지로 3가 조명거리 뒷골목",
    areaName: "을지로",
    latitude: 37.5668,
    longitude: 126.9922,
    type: "walk",
    moods: ["discover", "walk"],
    indoor: false,
    minStayMinutes: 20,
    idealStayMinutes: 35,
    maxStayMinutes: 55,
    estimatedCostWon: 0,
    openTime: "00:00",
    closeTime: "24:00",
    verifiedAt: "2026-09-12",
    accessibility: { seating: false },
  },
  {
    id: "seun-sangga-deck-walkway",
    name: "세운상가 공중보행로 데크",
    areaName: "종로·세운",
    latitude: 37.5702,
    longitude: 126.9959,
    type: "view",
    moods: ["walk", "discover", "stay"],
    indoor: false,
    minStayMinutes: 20,
    idealStayMinutes: 35,
    maxStayMinutes: 60,
    estimatedCostWon: 0,
    openTime: "09:00",
    closeTime: "22:00",
    verifiedAt: "2026-09-12",
    accessibility: { wheelchair: true, seating: true },
  },
  {
    id: "tapgol-park-monument",
    name: "탑골공원 원각사지 십층석탑 쉼터",
    areaName: "종로3가",
    latitude: 37.5713,
    longitude: 126.9882,
    type: "park",
    moods: ["empty", "walk"],
    indoor: false,
    minStayMinutes: 15,
    idealStayMinutes: 25,
    maxStayMinutes: 40,
    estimatedCostWon: 0,
    openTime: "09:00",
    closeTime: "18:00",
    verifiedAt: "2026-09-12",
    accessibility: { wheelchair: true, seating: true },
  },
  {
    id: "dada-bookstore-lounge",
    name: "인사동 누리사랑방 서가",
    areaName: "인사동",
    latitude: 37.5750,
    longitude: 126.9855,
    type: "library",
    moods: ["stay", "discover"],
    indoor: true,
    minStayMinutes: 15,
    idealStayMinutes: 30,
    maxStayMinutes: 50,
    estimatedCostWon: 0,
    openTime: "10:30",
    closeTime: "20:00",
    verifiedAt: "2026-09-12",
    accessibility: { wheelchair: true, seating: true },
  },
  {
    id: "jeongdong-church-garden",
    name: "정동제일교회 붉은벽돌 정원",
    areaName: "정동·시청",
    latitude: 37.5647,
    longitude: 126.9731,
    type: "walk",
    moods: ["empty", "walk"],
    indoor: false,
    minStayMinutes: 10,
    idealStayMinutes: 20,
    maxStayMinutes: 35,
    estimatedCostWon: 0,
    openTime: "00:00",
    closeTime: "24:00",
    verifiedAt: "2026-09-12",
    accessibility: { seating: true },
  },
  {
    id: "jungmyeongjeon-hall-terrace",
    name: "덕수궁 중명전 야외 테라스",
    areaName: "정동·서대문",
    latitude: 37.5661,
    longitude: 126.9712,
    type: "view",
    moods: ["empty", "discover"],
    indoor: false,
    minStayMinutes: 15,
    idealStayMinutes: 30,
    maxStayMinutes: 45,
    estimatedCostWon: 0,
    openTime: "09:30",
    closeTime: "17:30",
    closedDays: ["월요일"],
    verifiedAt: "2026-09-12",
    accessibility: { seating: true },
  },
  {
    id: "seodaemun-independence-park-trail",
    name: "돈의문박물관마을 골목길",
    areaName: "신문로·서대문",
    latitude: 37.5687,
    longitude: 126.9685,
    type: "walk",
    moods: ["walk", "discover"],
    indoor: false,
    minStayMinutes: 20,
    idealStayMinutes: 35,
    maxStayMinutes: 60,
    estimatedCostWon: 0,
    openTime: "10:00",
    closeTime: "19:00",
    closedDays: ["월요일"],
    verifiedAt: "2026-09-12",
    accessibility: { seating: true },
  },
  {
    id: "namdaemun-market-rooftop-view",
    name: "숭례문 앞 광장과 성곽 쉼터",
    areaName: "남대문·서울역",
    latitude: 37.5599,
    longitude: 126.9753,
    type: "walk",
    moods: ["walk", "empty"],
    indoor: false,
    minStayMinutes: 15,
    idealStayMinutes: 25,
    maxStayMinutes: 45,
    estimatedCostWon: 0,
    openTime: "00:00",
    closeTime: "24:00",
    verifiedAt: "2026-09-12",
    accessibility: { wheelchair: true, seating: true },
  },
  {
    id: "seoullo-7017-sky-garden",
    name: "서울로7017 공중정원 장미마당",
    areaName: "서울역·회현",
    latitude: 37.5568,
    longitude: 126.9723,
    type: "park",
    moods: ["walk", "empty", "stay"],
    indoor: false,
    minStayMinutes: 20,
    idealStayMinutes: 35,
    maxStayMinutes: 60,
    estimatedCostWon: 0,
    openTime: "00:00",
    closeTime: "24:00",
    verifiedAt: "2026-09-12",
    accessibility: { wheelchair: true, seating: true },
  },
  {
    id: "baekbeom-square-namsan-slope",
    name: "남산 백범광장 초입 잔디언덕",
    areaName: "남산·회현",
    latitude: 37.5552,
    longitude: 126.9796,
    type: "view",
    moods: ["empty", "walk", "stay"],
    indoor: false,
    minStayMinutes: 25,
    idealStayMinutes: 45,
    maxStayMinutes: 80,
    estimatedCostWon: 0,
    openTime: "00:00",
    closeTime: "24:00",
    verifiedAt: "2026-09-12",
    accessibility: { seating: true },
  },
  {
    id: "arc-n-book-euljiro-lounge",
    name: "을지로 페럼타워 도심 속 썬큰가든",
    areaName: "을지로·명동",
    latitude: 37.5670,
    longitude: 126.9842,
    type: "park",
    moods: ["stay", "empty"],
    indoor: false,
    minStayMinutes: 10,
    idealStayMinutes: 25,
    maxStayMinutes: 40,
    estimatedCostWon: 0,
    openTime: "00:00",
    closeTime: "24:00",
    verifiedAt: "2026-09-12",
    accessibility: { wheelchair: true, seating: true },
  },
];
